name: Build Android

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android NDK (Via SDK Manager)
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.2.1 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
          haxelib install flixel-ui 2.4.0 --quiet
          haxelib install hscript 2.5.0 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --quiet
          haxelib git extension-androidtools https://github.com/M.A.J.O.R.-Team/extension-androidtools --quiet
          haxelib run lime setup -y
          haxelib run lime setup flixel

      - name: Configure Lime Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_HOME/ndk/25.2.9519653

      - name: Compile APK
        run: |
          haxelib run lime build android -final

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VsSonicExe-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
